### ISSUE TITLE
PHP8.1支持

### ISSUE THREAD

**Issue by gitee1** [aogg/composer-PHPUnit-ThinkPHP#1]
能支持以下PHP8.1吗？目前使用的环境是ThinkPHP6.1，PHP8.1.26，无法安装

**Comment by aogg** [comment]
还没测试过哦，报错内容发下

**Comment by gitee1** [comment]
![image](https://github.com/aogg/composer-PHPUnit-ThinkPHP/assets/38205338/32863706-7746-48a5-9382-1181aff08d90)
是依赖的phpunit/phpunit版本问题，phpunit/phpunit7.X的版本好像不支持8.1

**Comment by aogg** [comment]
<img width="891" alt="image" src="https://github.com/aogg/composer-PHPUnit-ThinkPHP/assets/8998031/44206737-177b-40c1-b99d-f5a3ae666415">
tp官方也是，你这特殊需求看下composer能强制忽略不

**Comment by aogg** [comment]
好了，看下能用了没

**Comment by gitee1** [comment]
> 好了，看下能用了没

安装成功 :smile:
