### ISSUE TITLE
parse_str第一个参数为null，抛出异常

### ISSUE THREAD

**Issue by gitee1** [aogg/composer-PHPUnit-ThinkPHP#2]
环境PHP8.1<br/>
当$uri不包含get参数时，parse_url($uri, PHP_URL_QUERY)结果为null。aogg\phpunit\think\traits\CrawlerTrait类，line146，parse_str第一个参数为null，会抛出异常
![image](https://github.com/aogg/composer-PHPUnit-ThinkPHP/assets/38205338/0332c881-8d28-413c-89eb-083ce7e0e100)

**Comment by aogg** [comment]
https://packagist.org/packages/aogg/think-phpunit#v0.1.1
